const products = [
    {
      id: 1,
      name: "Apple",
      category: "Fruit",
      description: "Г/Ц Блинчики с мясом вес, Россия ",
      price: 89,
      rating: 5,
      discount: 0,
      image: "./images/card_img/blin.png",
      country: "Uzb",
    },
    {
      id: 2,
      name: "milk",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст. питьевое цельное...",
      price: 71,
      rating: 5,
      discount: 20,
      image: "./images/card_img/moloko.png",
    },
    {
      id: 3,
      name: "sausage",
      category: "meat",
      description:
        "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ...",
      price: 88,
      rating: 5,
      discount: 20,
      image: "./images/card_img/kolobasa.png",
    },
    {
      id: 4,
      name: "sausage",
      category: "meat",
      description:
        "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные...",
      price: 94,
      rating: 4.5,
      discount: 20,
      image: "./images/card_img/kolobasa.png",
    },
    {
      id: 5,
      name: "sausage",
      category: "meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 82,
      rating: 5,
      discount: 20,
      image: "./images/card_img/kolbasa_palka.png",
    },
    {
      id: 6,
      name: "sausage",
      category: "meat",
      description:
        "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ...",
      price: 91,
      rating: 3.5,
      discount: 50,
      image: "./images/card_img/kolobasa.png",
    },
    {
      id: 7,
      name: "Chicken",
      category: "Meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 68,
      rating: 3.5,
      discount: 20,
      image: "./images/card_img/kolobasa.png",
    },
    {
      id: 8,
      name: "Chocolate",
      category: "dairy",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 61,
      rating: 4.5,
      discount: 20,
      image: "./images/card_img/moloko.png",
    },
    {
      id: 9,
      name: "sausage",
      category: "meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 98,
      rating: 5,
      discount: 20,
      image: "./images/card_img/kolbasa_desna.png",
    },
    {
      id: 10,
      name: "Egg",
      category: "meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 79,
      rating: 4.5,
      discount: 0,
      image: "./images/card_img/kolobasa.png",
    },
    {
      id: 11,
      name: "Fish",
      category: "Meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 89,
      rating: 3.5,
      discount: 50,
      image: "./images/card_img/kolbasa_palka.png",
    },
    {
      id: 12,
      name: "milk",
      category: "dairy",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 61,
      rating: 4,
      discount: 20,
      image: "./images/card_img/moloko.png",
    },
    {
      id: 13,
      name: "Grilled Cheese",
      category: "fruit",
      description:
        "Г/Ц Блинчики с мясом вес, Россия",
      price: 100,
      rating: 5,
      discount: 50,
      image: "./images/card_img/blin.png",
    },
    {
      id: 14,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 63,
      rating: 4.5,
      discount: 20,
      image: "./images/card_img/moloko.png",
    },
  ];