const products = [
    {
      id: 1,
      name: "Apple",
      category: "Fruit",
      description: "Г/Ц Блинчики с мясом вес, Россия ",
      price: 89,
      rating: 5,
      discount: 0,
      isNew:  true,
      image: "../images/card_img/blin.png",
      country: "Uzb",
    },
    {
      id: 2,
      name: "milk",
      category: "dairy",  
      description:
        "Молоко ПРОСТОКВАШИНО паст. питьевое цельное...",
      price: 71,
      rating: 5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 3,
      name: "sausage",
      category: "meat",
      description:
        "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ...",
      price: 88,
      rating: 5,
      discount: 20,
      isNew:  true,
      image: "../images/card_img/kolobasa.png",
    },
    {
      id: 4,
      name: "sausage",
      category: "meat",
      description:
        "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные...",
      price: 94,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolobasa.png",
    },
    {
      id: 5,
      name: "sausage",
      category: "meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 82,
      rating: 5,
      discount: 20,
      isNew:  true,
      image: "../images/card_img/kolbasa_palka.png",
    },
    {
      id: 6,
      name: "sausage",
      category: "meat",
      description:
        "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ...",
      price: 0,
      rating: 3.5,
      discount: 50,
      isNew: false,
      image: "../images/card_img/kolobasa.png",
    },
    {
      id: 7,
      name: "Chicken",
      category: "Meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 68,
      rating: 3.5,
      discount: 20,
      isNew:  true,
      image: "../images/card_img/kolobasa.png",
    },
    {
      id: 8,
      name: "Chocolate",
      category: "dairy",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 0,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 9,
      name: "sausage",
      category: "meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 98,
      rating: 5,
      discount: 20,
      isNew:  true,
      image: "../images/card_img/kolbasa_desna.png",
    },
    {
      id: 10,
      name: "Egg",
      category: "meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 79,
      rating: 4.5,
      discount: 0,
      isNew: false,
      image: "../images/card_img/kolobasa.png",
    },
    {
      id: 11,
      name: "Fish",
      category: "Meat",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 0,
      rating: 3.5,
      discount: 50,
      isNew:  true,
      image: "../images/card_img/kolbasa_palka.png",
    },
    {
      id: 12,
      name: "milk",
      category: "dairy",
      description:
        "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
      price: 61,
      rating: 4,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 13,
      name: "Grilled Cheese",
      category: "fruit",
      description:
        "Г/Ц Блинчики с мясом вес, Россия",
      price: 100,
      rating: 5,
      discount: 50,
      isNew:  true,
      image: "../images/card_img/blin.png",
    },
    {
      id: 14,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 20,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 15,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 30,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/blin.png",
    },
    {
      id: 16,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 40,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 17,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 50,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolobasa.png",
    },
    {
      id: 18,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 340,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 19,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 40,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolbasa_palka.png",
    },
    {
      id: 20,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 320,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 21,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 120,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolbasa_desna.png",
    },
    {
      id: 22,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 120,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/blin.png",
    },
    {
      id: 23,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 230,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolobasa.png",
    },
    {
      id: 24,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 340,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolbasa_palka.png",
    },
    {
      id: 25,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 40,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/blin.png",
    },
    {
      id: 26,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 210,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 27,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 120,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolbasa_desna.png",
    },
    {
      id: 28,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 130,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/blin.png",
    },
    {
      id: 29,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 310,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/moloko.png",
    },
    {
      id: 30,
      name: "Steak",
      category: "dairy",
      description:
        "Молоко ПРОСТОКВАШИНО паст.питьевое цельное...",
      price: 120,
      rating: 4.5,
      discount: 20,
      isNew: false,
      image: "../images/card_img/kolbasa_palka.png",
    },
  ];